services:
  network-deploy-service:
    networks:
      - tanmaybank
  microservice-base-config:
    extends:
      service: network-deploy-service
      environment:
        SPRING_PROFILES_ACTIVE: default
  microservice-configserver-config:
    extends:
      service: microservice-base-config
      depends_on:
      configserver:
        condition: service_healthy